### ISSUE TITLE
app not updated with last repo

### ISSUE THREAD

**Issue by Denkishi** [giacomoferretti/ffapi-project#10]
![c6e71e2c-4545-457c-bbaa-cd57bb25f029](https://user-images.githubusercontent.com/20754887/66199582-3a12a600-e69f-11e9-9626-fe5343b65adb.jpg)

**Comment by giacomoferretti** [comment]
The server is still offline due to maintenance.

**Comment by giacomoferretti** [comment]
The server is up and running!
